server:
  port: 8081
  servlet:
    session:
      store-type: jdbc
      jdbc:
        initialize-schema: never
      timeout: 360000

spring:
  application:
    name: MES_NEW
  profiles:
    active: dev
  devtools:
    livereload:
      enabled: true
  datasource:
    url: jdbc:sqlserver://192.168.50.237:1433;databaseName=jct_mes;encrypt=true;trustServerCertificate=true
    username: jct_admin
    password: jinco!@34
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  servlet:
    multipart:
      enabled: true
      location: d:/mesUploads
  jackson:
    time-zone: Asia/Seoul
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    check-template-location: true
    mode: HTML
    cache: false
    template-resolver-order: 0
  freemarker:
    template-loader-path: classpath:/freemarker/
    suffix: .ftl
    charset: UTF-8
    cache: false
    content-type: text/html
file:
  upload-dir: d:/mesUploads

logging:
  level:
    root: INFO           # 기본 로그 레벨
    p6spy: DEBUG         # p6spy 로거 활성화 (INFO 이상 다 보이게)
    org.mybatis: INFO    # MyBatis 쿼리 로그는 잠깐 죽여도 됨 (원하면 DEBUG로 다시)
    org.springframework: DEBUG
    com.jct.mes_new: DEBUG

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-handlers-package: com.jct.mes_new.mapper.typehandler
  type-aliases-package: com.jct.mes_new.entity
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 30
    # log-impl 제거 (p6spy 에게 맡김)

app:
  webclient:
    baseUrl: https://sboapiCD.ecounterp.com/OAPI/V2
  logs:
    fixedRate: false
    save: false
    send: false
decorator:
  datasource:
    enabled: true
    p6spy:
      enable-logging: true
      logging: slf4j
